In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/pradeep/Downloads/data_to_fit.csv')

/var/folders/1_/8z7nsr3d0_d_4g3l303jw0yh0000gp/T/ipykernel_1561/2382629478.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/manavisharma/Downloads/data_to_fit.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 337984 entries, 0 to 337983
Columns: 140 entries, retailer_id to ppg_nm__retailer_id
dtypes: float64(74), int64(47), object(19)
memory usage: 361.0+ MB

In [5]:
df.head()

,retailer_id,ppg_nm,week_number,log_price,log_acv_wtd_distribution,month,acv_tpr_by_100,acv_display_by_100,acv_feature_and_display_by_100,acv_feature_by_100,...,promo_flag,Peak_Holiday_2_weeks_before_Christmas,Peak_Holiday_Easter,Peak_Holiday_Second_week_of_the_year,Peak_Holiday_Thanksgiving,Peak_Holiday_Two_Week_After_Thanksgiving,Peak_Holiday_Week_After_Thanksgiving,Dip_Holiday_Valentine_Week,vol_total,ppg_nm__retailer_id
0,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,1,-0.369417,2.140461,11,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,23665.0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
1,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,2,-0.369731,2.190605,11,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,23665.0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
2,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,6,-0.378265,2.301774,12,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,23665.0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
3,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,7,-0.370581,2.143996,1,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,23665.0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
4,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,8,-0.378107,1.996163,1,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,23665.0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...

In [6]:
print(df.columns.tolist())

['retailer_id', 'ppg_nm', 'week_number', 'log_price', 'log_acv_wtd_distribution', 'month', 'acv_tpr_by_100', 'acv_display_by_100', 'acv_feature_and_display_by_100', 'acv_feature_by_100', 'promo_flag_outlier_retailers', 'pl1', 'pl2', 'pl3', 'Peak_on_New_Year', 'Dip_on_New_Year', 'Dip_on_Thanksgiving', 'Peak_on_Thanksgiving', 'Dip_1_week_after_Thanksgiving', 'Peak_1_week_after_Thanksgiving', 'Dip_2_week_after_Thanksgiving', 'Peak_2_week_after_Thanksgiving', 'Dip_on_Christmas', 'Peak_on_Christmas', 'Dip_in_2nd_week_of_year', 'Peak_1_week_after_Halloween', 'Peak_on_4th_of_July', 'covid_period', 'covid_flag_3', 'covid_flag_4', 'log_net_sales_volume', 'loess_p4', 'p_log_net_sales_volume', 'estimate_4', 'trend_term', 'loess_predicted_log_net_sales_volume', 'product_pack_count', 'brand_nm', 'unit_of_measurement', 'product_attr3', 'manufacturer_nm', 'product_category', 'subbrand_nm', 'product_unit_size', 'period_id', 'net_sales_volume', 'net_sales_with_taxes', 'product_metric_1', 'promo_sales_volume', 'acv_any_promo', 'acv_display', 'acv_feature', 'acv_feature_and_display', 'acv_tpr', 'acv_wtd_distribution', 'date', 'full_date', 'week', 'monthname', 'year', 'year_month', 'year_week', 'min_date', 'continous_year', 'month_number', 'continous_day', 'pair', 'price', 'promo_flag2', 'Complement_Promo_flag2', 'Non_Promo_Weeks', 'Model_Used', 'edlp_price_hist', 'edlp_price_fut', 'edlp_final', 'edlp_price', 'max_price', 'discount_percentage', 'avg_volume', 'total_value', 'pct_value', 'cum_percent', 'cumulative_flag', 'general_flag', 'week_count', 'cv_price', 'p2', 'p5', 'p95', 'p98', 'p99', 'avg_items', 'smooth_avg_items', 'log_avg_items', 'log_smooth_avg_items', 'acv_display_log', 'acv_feature_and_display_log', 'acv_tpr_log', 'acv_feature_log', 'smooth_acv', 'acv_diff', 'log_smooth_acv', 'log_acv_diff', 'log_acv_any_promo', 'total_volume', 'cpi', 'log_cpi', 'total_value_manuf', 'total_volume_manuf', 'opi', 'log_opi', 'sequence_opi', 'edlp_opi', 'total_value_xpi', 'total_volume_xpi', 'xpi', 'log_xpi', 'peak_flag', 'vol_19', 'peak19', 'peak_flag19', 'vol_20', 'peak20', 'peak_flag20', 'vol_21', 'peak21', 'peak_flag21', 'vol_22', 'peak22', 'peak_flag22', 'promo_flag', 'Peak_Holiday_2_weeks_before_Christmas', 'Peak_Holiday_Easter', 'Peak_Holiday_Second_week_of_the_year', 'Peak_Holiday_Thanksgiving', 'Peak_Holiday_Two_Week_After_Thanksgiving', 'Peak_Holiday_Week_After_Thanksgiving', 'Dip_Holiday_Valentine_Week', 'vol_total', 'ppg_nm__retailer_id']

In [7]:
df.tail()

,retailer_id,ppg_nm,week_number,log_price,log_acv_wtd_distribution,month,acv_tpr_by_100,acv_display_by_100,acv_feature_and_display_by_100,acv_feature_by_100,...,promo_flag,Peak_Holiday_2_weeks_before_Christmas,Peak_Holiday_Easter,Peak_Holiday_Second_week_of_the_year,Peak_Holiday_Thanksgiving,Peak_Holiday_Two_Week_After_Thanksgiving,Peak_Holiday_Week_After_Thanksgiving,Dip_Holiday_Valentine_Week,vol_total,ppg_nm__retailer_id
337979,WEGMANS,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...,146,-1.159303,4.445471,09,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,958368.18,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337980,WEGMANS,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...,148,-1.160971,4.443956,09,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,958368.18,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337981,WEGMANS,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...,149,-1.160915,4.440012,09,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,958368.18,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337982,WEGMANS,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...,151,-1.159237,4.368232,10,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,958368.18,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337983,dummy,dummy,1,-0.369417,2.140461,dummy,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,23665.00,dummy__dummy

In [8]:
df  = df.drop(df.index[-1])

# feature engineering

In [9]:
#adding seasonality flags

In [10]:
df['period_id'] = pd.to_datetime(df['period_id'])
df_month_dummies = pd.get_dummies(df['period_id'].dt.month_name(), prefix='month')
df = pd.concat([df, df_month_dummies], axis=1)
print(df)

       retailer_id                                             ppg_nm  \
0            AHOLD  AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
1            AHOLD  AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
2            AHOLD  AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
3            AHOLD  AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
4            AHOLD  AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...
...            ...                                                ...
337978     WEGMANS  WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337979     WEGMANS  WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337980     WEGMANS  WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337981     WEGMANS  WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337982     WEGMANS  WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...

        week_number  log_price  log_acv_wtd_distribution month  \
0                 1  -0.369417                  2.140461    11
1                 2  -0.369731                  2.190605    11
2                 6  -0.378265                  2.301774    12
3                 7  -0.370581                  2.143996     1
4                 8  -0.378107                  1.996163     1
...             ...        ...                       ...   ...
337978          145  -1.161862                  4.462604    08
337979          146  -1.159303                  4.445471    09
337980          148  -1.160971                  4.443956    09
337981          149  -1.160915                  4.440012    09
337982          151  -1.159237                  4.368232    10

        acv_tpr_by_100  acv_display_by_100  acv_feature_and_display_by_100  \
0                  0.0                 0.0                             0.0
1                  0.0                 0.0                             0.0
2                  0.0                 0.0                             0.0
3                  0.0                 0.0                             0.0
4                  0.0                 0.0                             0.0
...                ...                 ...                             ...
337978             0.0                 0.0                             0.0
337979             0.0                 0.0                             0.0
337980             0.0                 0.0                             0.0
337981             0.0                 0.0                             0.0
337982             0.0                 0.0                             0.0

        acv_feature_by_100  ...  month_December  month_February  \
0                      0.0  ...               0               0
1                      0.0  ...               0               0
2                      0.0  ...               1               0
3                      0.0  ...               0               0
4                      0.0  ...               0               0
...                    ...  ...             ...             ...
337978                 0.0  ...               0               0
337979                 0.0  ...               0               0
337980                 0.0  ...               0               0
337981                 0.0  ...               0               0
337982                 0.0  ...               0               0

        month_January  month_July  month_June  month_March  month_May  \
0                   0           0           0            0          0
1                   0           0           0            0          0
2                   0           0           0            0          0
3                   1           0           0            0          0
4                   1           0           0            0          0
...               ...         ...         ...          ...        ...
337978              0           0           0            0          0
337979              0           0           0            0          0
337980              0           0           0            0          0
337981              0           0           0            0          0
337982              0           0           0            0          0

        month_November  month_October  month_September
0                    1              0                0
1                    1              0                0
2                    0              0                0
3                    0              0                0
4                    0              0                0
...                ...            ...              ...
337978               0              0                0
337979               0              0                1
337980               0              0                1
337981               0              0                1
337982               0              1                0

[337983 rows x 152 columns]

In [11]:
# adding ppg_retailer column

In [12]:
df['ppg_retailer'] = df['ppg_nm'] + ' ' +  df['retailer_id']

In [13]:
df.isna().sum()

retailer_id                 0
ppg_nm                      0
week_number                 0
log_price                   0
log_acv_wtd_distribution    0
                           ..
month_May                   0
month_November              0
month_October               0
month_September             0
ppg_retailer                0
Length: 153, dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 337983 entries, 0 to 337982
Columns: 153 entries, retailer_id to ppg_retailer
dtypes: datetime64[ns](1), float64(74), int64(47), object(19), uint8(12)
memory usage: 367.5+ MB

In [21]:
df.tail(2)

,retailer_id,ppg_nm,week_number,log_price,log_acv_wtd_distribution,month,acv_tpr_by_100,acv_display_by_100,acv_feature_and_display_by_100,acv_feature_by_100,...,month_February,month_January,month_July,month_June,month_March,month_May,month_November,month_October,month_September,ppg_retailer
337981,WEGMANS,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...,149,-1.160915,4.440012,09,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...
337982,WEGMANS,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...,151,-1.159237,4.368232,10,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,WOOD FLOOR CLEANERS | PUMP | BONA | BONA SB | ...

In [29]:
path = '/Users/manavisharma/Downloads/fe1.csv'  
df.to_csv(path)

# model

In [16]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [16]:
# #fixed effects:

# #seasonality
# month_April
# month_August
# month_December
# month_February
# month_January
# month_July
# month_June
# month_March
# month_May
# month_November
# month_October
# month_September

# #holiday_flags
# Peak_on_New_Year ok
# Dip_on_New_Year  ok
# Dip_on_Thanksgiving ok
 Peak_on_Thanksgiving
# Dip_1_week_after_Thanksgiving ok 
# Peak_2_week_after_Thanksgiving ok
# Dip_on_Christmas ok 
# Peak_on_Christmas ok 
# Dip_in_2nd_week_of_year ok 
 Peak_1_week_after_Halloween

# #covid_flags:
# covid_flag_3 
# covid_flag_4

In [17]:
# #random effects:

# log_price
#trend_term


# #pantry loading flags:
# pl1
# pl2
# pl3 

# #promo flags
# acv_display_by_100 
# acv_feature_by_100 
# acv_feature_and_display_by_100 
# acv_tpr_by_100 
# log_acv_wtd_distribution 

# #cannibalisation terms
# log_opi 
# log_xpi

In [18]:
# hlm with 2 levels:
# l1 = ppg_retailer
# l2 = retailer

In [19]:
fixed_effects= "log_net_sales_volume~log_price + month_April+ month_August+ month_December+ month_February+ month_January +  month_July+ month_June+ month_March+ month_May+month_November+ month_October+ month_September + Peak_on_New_Year+ Dip_on_New_Year + Dip_on_Thanksgiving + Peak_on_Thanksgiving+ Dip_1_week_after_Thanksgiving + Peak_1_week_after_Thanksgiving+ Dip_2_week_after_Thanksgiving+ Peak_2_week_after_Thanksgiving + Dip_on_Christmas + Peak_on_Christmas+ Dip_in_2nd_week_of_year + Peak_1_week_after_Halloween + Peak_on_4th_of_July + covid_period+ covid_flag_3 + covid_flag_4"
random_effects="~log_acv_wtd_distribution + log_price + acv_display_by_100+ acv_feature_and_display_by_100+acv_tpr_by_100 + acv_feature_by_100 +trend_term+pl1+pl2+pl3"

In [23]:
md = smf.mixedlm(fixed_effects,df, groups=df["retailer_id"],re_formula=random_effects,vc_formula={'retailer_id': '0 + C(retailer_id)'})

In [24]:
mdf = md.fit(method="powell")
print(mdf.summary())

/Users/manavisharma/anaconda3/lib/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2261: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

                                         Mixed Linear Model Regression Results
=======================================================================================================================
Model:                               MixedLM                  Dependent Variable:                  log_net_sales_volume
No. Observations:                    337983                   Method:                              REML
No. Groups:                          21                       Scale:                               0.7257
Min. group size:                     33                       Log-Likelihood:                      -426213.4104
Max. group size:                     44348                    Converged:                           Yes
Mean group size:                     16094.4
-----------------------------------------------------------------------------------------------------------------------
                                                               Coef.    Std.Err.    z    P>|z|    [0.025       0.975]
-----------------------------------------------------------------------------------------------------------------------
Intercept                                                       5.447 1482284.432  0.000 1.000 -2905218.654 2905229.548
log_price                                                      -0.564
month_April                                                    -0.219 1482284.432 -0.000 1.000 -2905224.320 2905223.882
month_August                                                   -0.048 1482284.432 -0.000 1.000 -2905224.149 2905224.053
month_December                                                 -0.125 1482284.432 -0.000 1.000 -2905224.226 2905223.976
month_February                                                 -0.171 1482284.432 -0.000 1.000 -2905224.272 2905223.930
month_January                                                  -0.103 1482284.432 -0.000 1.000 -2905224.204 2905223.997
month_July                                                     -0.117 1482284.432 -0.000 1.000 -2905224.217 2905223.984
month_June                                                     -0.137 1482284.432 -0.000 1.000 -2905224.238 2905223.964
month_March                                                    -0.115 1482284.432 -0.000 1.000 -2905224.216 2905223.986
month_May                                                      -0.208 1482284.432 -0.000 1.000 -2905224.309 2905223.892
month_November                                                 -0.063 1482284.432 -0.000 1.000 -2905224.164 2905224.037
month_October                                                  -0.064 1482284.432 -0.000 1.000 -2905224.165 2905224.037
month_September                                                -0.072 1482284.432 -0.000 1.000 -2905224.173 2905224.029
Peak_on_New_Year                                                0.032       0.013  2.537 0.011        0.007       0.057
Dip_on_New_Year                                                -0.040       0.030 -1.347 0.178       -0.099       0.018
Dip_on_Thanksgiving                                            -0.098       0.027 -3.636 0.000       -0.150      -0.045
Peak_on_Thanksgiving                                            0.018       0.034  0.522 0.602       -0.050       0.086
Dip_1_week_after_Thanksgiving                                  -0.008       0.018 -0.430 0.667       -0.043       0.028
Peak_1_week_after_Thanksgiving                                 -0.005       0.040 -0.120 0.904       -0.083       0.073
Dip_2_week_after_Thanksgiving                                  -0.012       0.050 -0.247 0.805       -0.110       0.085
Peak_2_week_after_Thanksgiving                                  0.017       0.035  0.488 0.625       -0.051       0.085
Dip_on_Christmas                                               -0.055       0.028 -1.954 0.051       -0.110       0.000
Peak_on_Christmas                                              -0.003       0.030 -0.084 0.933       -0.062       0.057
Dip_in_2nd_week_of_year                                         0.022       0.030  0.722 0.470       -0.038       0.082
Peak_1_week_after_Halloween                                    -0.049       0.052 -0.943 0.345       -0.151       0.053
Peak_on_4th_of_July                                             0.037       0.042  0.883 0.377       -0.046       0.120
covid_period                                                    0.283       0.006 48.246 0.000        0.272       0.295
covid_flag_3                                                    0.244       0.019 12.801 0.000        0.207       0.281
covid_flag_4                                                    0.364       0.008 46.734 0.000        0.349       0.379
Group Var                                                       3.357     159.326
Group x log_acv_wtd_distribution Cov                           -1.213       0.315
log_acv_wtd_distribution Var                                    1.164       0.322
Group x log_price Cov                                          -0.000       0.557
log_acv_wtd_distribution x log_price Cov                       -0.449
log_price Var                                                   1.003
Group x acv_display_by_100 Cov                                -11.249       0.259
log_acv_wtd_distribution x acv_display_by_100 Cov               3.322       1.591
log_price x acv_display_by_100 Cov                              0.462
acv_display_by_100 Var                                         66.675
Group x acv_feature_and_display_by_100 Cov                     -4.746       0.628
log_acv_wtd_distribution x acv_feature_and_display_by_100 Cov   1.992
log_price x acv_feature_and_display_by_100 Cov                 -0.171       1.327
acv_display_by_100 x acv_feature_and_display_by_100 Cov        15.620       8.416
acv_feature_and_display_by_100 Var                              7.541
Group x acv_tpr_by_100 Cov                                      0.000
log_acv_wtd_distribution x acv_tpr_by_100 Cov                   0.000       0.100
log_price x acv_tpr_by_100 Cov                                  0.000
acv_display_by_100 x acv_tpr_by_100 Cov                         0.000
acv_feature_and_display_by_100 x acv_tpr_by_100 Cov             0.000       0.380
acv_tpr_by_100 Var                                              0.726
Group x acv_feature_by_100 Cov                                 -0.000
log_acv_wtd_distribution x acv_feature_by_100 Cov               0.000       0.126
log_price x acv_feature_by_100 Cov                              0.000
acv_display_by_100 x acv_feature_by_100 Cov                     0.000
acv_feature_and_display_by_100 x acv_feature_by_100 Cov         0.000
acv_tpr_by_100 x acv_feature_by_100 Cov                         0.000
acv_feature_by_100 Var                                          0.726
Group x trend_term Cov                                          0.000       0.773
log_acv_wtd_distribution x trend_term Cov                       0.000       0.200
log_price x trend_term Cov                                      0.000
acv_display_by_100 x trend_term Cov                             0.000
acv_feature_and_display_by_100 x trend_term Cov                 0.000       1.851
acv_tpr_by_100 x trend_term Cov                                 0.000
acv_feature_by_100 x trend_term Cov                             0.000
trend_term Var                                                  0.726
Group x pl1 Cov                                                 0.000       0.829
log_acv_wtd_distribution x pl1 Cov                              0.000       0.204
log_price x pl1 Cov                                             0.000
acv_display_by_100 x pl1 Cov                                    0.000
acv_feature_and_display_by_100 x pl1 Cov                        0.000       1.995
acv_tpr_by_100 x pl1 Cov                                        0.000
acv_feature_by_100 x pl1 Cov                                    0.000
trend_term x pl1 Cov                                           -0.000
pl1 Var                                                         0.726
Group x pl2 Cov                                                 0.000       0.835
log_acv_wtd_distribution x pl2 Cov                              0.000       0.205
log_price x pl2 Cov                                             0.000
acv_display_by_100 x pl2 Cov                                    0.000
acv_feature_and_display_by_100 x pl2 Cov                        0.000       2.000
acv_tpr_by_100 x pl2 Cov                                        0.000
acv_feature_by_100 x pl2 Cov                                    0.000
trend_term x pl2 Cov                                            0.000
pl1 x pl2 Cov                                                   0.000
pl2 Var                                                         0.726
Group x pl3 Cov                                                 0.000       0.826
log_acv_wtd_distribution x pl3 Cov                              0.000       0.202
log_price x pl3 Cov                                             0.000
acv_display_by_100 x pl3 Cov                                    0.000
acv_feature_and_display_by_100 x pl3 Cov                        0.000       1.972
acv_tpr_by_100 x pl3 Cov                                        0.000
acv_feature_by_100 x pl3 Cov                                    0.000
trend_term x pl3 Cov                                            0.000
pl1 x pl3 Cov                                                   0.000
pl2 x pl3 Cov                                                   0.000
pl3 Var                                                         0.726
retailer_id Var                                                 0.726     159.251
=======================================================================================================================

/Users/manavisharma/anaconda3/lib/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2705: RuntimeWarning: invalid value encountered in sqrt
  sdf[0:self.k_fe, 1] = np.sqrt(np.diag(self.cov_params()[0:self.k_fe]))

In [24]:
#formula = 'log_net_sales_volume ~ log_price + pl1 +pl2+ pl3+ acv_display_by_100 + acv_feature_by_100 + acv_feature_and_display_by_100 + acv_tpr_by_100 + log_acv_wtd_distribution + log_opi + log_xpi + month_April+ month_August+ month_December+ month_February+ month_January+ month_July+ month_June+ month_March+ month_May+month_November+ month_October+ month_September+Peak_on_New_Year+ Dip_on_New_Year+ Dip_on_Thanksgiving + Dip_1_week_after_Thanksgiving+ Peak_2_week_after_Thanksgiving+ Dip_on_Christmas+ Peak_on_Christmas+ Dip_in_2nd_week_of_year+ Peak_on_4th_of_July+ Peak_1_week_after_Thanksgiving+ Dip_2_week_after_Thanksgiving  + covid_flag_3+ covid_flag_4'

In [ ]:
 #month_July+ month_June+ month_March+ month_May+month_November+ month_October+ month_September

In [25]:
#model = smf.mixedlm(formula, data=df, groups=df['ppg_retailer'], re_formula='1 + log_price + pl1+ pl2+ pl3 + acv_display_by_100 + acv_feature_by_100 + acv_feature_and_display_by_100 + acv_tpr_by_100 + log_acv_wtd_distribution + log_opi + log_xpi', vc_formula={'retailer_id': '0 + C(retailer_id)'})

In [17]:
#result = model.fit()

In [18]:
#print(result.summary())

In [25]:
print(mdf.params)

Intercept               5.447195
log_price              -0.563812
month_April            -0.219008
month_August           -0.047809
month_December         -0.125178
                          ...
trend_term x pl3 Cov    0.000000
pl1 x pl3 Cov           0.000000
pl2 x pl3 Cov           0.000000
pl3 Var                 1.000000
retailer_id Var         1.000000
Length: 97, dtype: float64

In [26]:
predictions = mdf.predict(df)

In [27]:
df['predictions'] = predictions

In [28]:
print(df['ppg_retailer'].nunique())

3985

In [29]:
df.head()

,retailer_id,ppg_nm,week_number,log_price,log_acv_wtd_distribution,month,acv_tpr_by_100,acv_display_by_100,acv_feature_and_display_by_100,acv_feature_by_100,...,month_January,month_July,month_June,month_March,month_May,month_November,month_October,month_September,ppg_retailer,predictions
0,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,1,-0.369417,2.140461,11,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,5.592045
1,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,2,-0.369731,2.190605,11,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,5.592222
2,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,6,-0.378265,2.301774,12,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,5.535287
3,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,7,-0.370581,2.143996,1,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,5.584614
4,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,8,-0.378107,1.996163,1,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,5.556944

In [30]:
from sklearn.metrics import mean_absolute_percentage_error, r2_score

In [31]:
def calculate_mape(y_true, y_pred):
    return mean_absolute_percentage_error(y_true, y_pred)
def calculate_r2(y_true, y_pred):
    return r2_score(y_true, y_pred)

In [32]:
grouped = df.groupby('ppg_retailer')

In [33]:
mape_scores = grouped.apply(lambda x: calculate_mape(x['log_net_sales_volume'], x['predictions']))
r2_scores = grouped.apply(lambda x: calculate_r2(x['log_net_sales_volume'], x['predictions']))

In [34]:
results_df = pd.DataFrame({
    'MAPE': mape_scores,
    'R2 Score': r2_scores
})

print(results_df)

                                                        MAPE    R2 Score
ppg_retailer
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...  0.161939   -0.755767
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...  0.424934  -82.716439
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...  0.444024 -213.824120
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...  0.041344   -0.018942
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...  0.784380  -17.162255
...                                                      ...         ...
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...  0.163994   -1.092622
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...  0.223605  -49.707626
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...  0.364045 -171.922995
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...  0.325942  -76.840687
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...  0.261499  -25.654045

[3985 rows x 2 columns]

In [50]:
results_df = pd.DataFrame({
    'MAPE': mape_scores,
    'R2 Score': r2_scores
})

In [35]:
mape_threshold = 0.3  
r2_threshold = 0.45

In [36]:
results_df['MAPE'] = results_df['MAPE'] <= mape_threshold
results_df['R2 Score'] = results_df['R2 Score'] >= r2_threshold

In [37]:
print(results_df)

                                                     MAPE  R2 Score
ppg_retailer
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...   True     False
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...  False     False
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...  False     False
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...   True     False
AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM S...  False     False
...                                                   ...       ...
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...   True     False
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...   True     False
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...  False     False
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...  False     False
WOOD FLOOR CLEANERS | TRIGGER | MURPHY | MURPHY...   True     False

[3985 rows x 2 columns]

In [39]:
coefficients_data = {'ppg_retailer': [], 'price_coefficient': []}

for retailer_id in df['ppg_retailer'].unique():
    retailer_df = df[df['ppg_retailer'] == retailer_id]
    price_coefficient = mdf.params['log_price']
    coefficients_data['ppg_retailer'].append(retailer_id)
    coefficients_data['price_coefficient'].append(price_coefficient)
coefficients_df = pd.DataFrame(coefficients_data)

In [40]:
result_df = results_df.merge(coefficients_df, on='ppg_retailer')

In [41]:
def is_coefficient_between_range(coeff):
    return -5 <= coeff <= -0.5
result_df['Beta'] = result_df['price_coefficient'].apply(lambda x: is_coefficient_between_range(x))

In [42]:
result_df.head()

,ppg_retailer,MAPE,R2 Score,price_coefficient,Beta
0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,-0.563812,True
1,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,-0.563812,True
2,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,-0.563812,True
3,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,-0.563812,True
4,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,-0.563812,True

In [43]:
result_df['MAPE'].value_counts()

False    3138
True      847
Name: MAPE, dtype: int64

In [44]:
result_df['R2 Score'].value_counts()

False    3985
Name: R2 Score, dtype: int64

In [47]:
result_df['ppg_retailer'].nunique()

3516

In [48]:
result_df['final_flag'] = result_df['MAPE'] & result_df['R2 Score'] & result_df['Beta']

In [49]:
result_df.head()

,ppg_retailer,MAPE,R2 Score,price_coefficient,Beta,final_flag
0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,True,-0.569148,True,True
1,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,True,-0.569148,True,True
2,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,-0.569148,True,False
3,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,-0.569148,True,False
4,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,-0.569148,True,False

In [50]:
result_df['final_flag'].value_counts()

False    2683
True      833
Name: final_flag, dtype: int64

In [51]:
path = '/Users/manavisharma/Downloads/newrs.csv'  
result_df.to_csv(path, index_label='ppg_retailer')

In [94]:
#calculating coverage by retailer

In [95]:
df.head(1)

,ppg_nm,subbrand_nm,manufacturer_nm,product_pack_count,unit_of_measurement,product_attr3,period_id,product_category,brand_nm,retailer_id,...,month_January,month_July,month_June,month_March,month_May,month_November,month_October,month_September,ppg_retailer,predictions
0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,AE OZIUM SB,REM MANUFACTURER,1.0,OUNCE,AEROSOL,2019-11-09,SURFACE CARE,AE OZIUM,AHOLD,...,0,0,0,0,0,1,0,0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,8.264988

In [161]:
grouped_df = df.groupby('ppg_retailer')

In [163]:
grouped_df = df.groupby('ppg_retailer').agg(mean_score=('net_sales_with_taxes', 'mean')).reset_index()

In [176]:
grouped_df1 = grouped_df.merge(df[['ppg_nm', 'ppg_retailer','retailer_id']], on='ppg_retailer').drop_duplicates()

In [177]:
grouped_df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3625 entries, 0 to 389285
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ppg_retailer  3625 non-null   object
 1   mean_score    3625 non-null   float64
 2   ppg_nm        3625 non-null   object
 3   retailer_id   3625 non-null   object
dtypes: float64(1), object(3)
memory usage: 141.6+ KB

In [178]:
grouped_df1.head()

,ppg_retailer,mean_score,ppg_nm,retailer_id
0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,162.574052,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,AHOLD
153,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,26.687255,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,HY-VEE
306,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,6.472653,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,MEIJER
355,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,7647.868810,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,OTHER TOTAL US FOOD
508,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,2742.341046,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,MEIJER

In [179]:
result_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3625 entries, 0 to 3624
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ppg_retailer       3625 non-null   object
 1   MAPE               3625 non-null   bool
 2   R2 Score           3625 non-null   bool
 3   price_coefficient  3625 non-null   float64
 4   Beta               3625 non-null   bool
dtypes: bool(3), float64(1), object(1)
memory usage: 95.6+ KB

In [201]:
coverage_df = pd.merge(result_df,grouped_df1, on='ppg_retailer')

In [202]:
coverage_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3625 entries, 0 to 3624
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ppg_retailer       3625 non-null   object
 1   MAPE               3625 non-null   bool
 2   R2 Score           3625 non-null   bool
 3   price_coefficient  3625 non-null   float64
 4   Beta               3625 non-null   bool
 5   final_flag         3625 non-null   bool
 6   mean_score         3625 non-null   float64
 7   ppg_nm             3625 non-null   object
 8   retailer_id        3625 non-null   object
dtypes: bool(4), float64(2), object(3)
memory usage: 184.1+ KB

In [208]:
selected_columns = ['ppg_nm','retailer_id','ppg_retailer','MAPE','R2 Score','Beta','final_flag','mean_score']

In [209]:
cov_df = coverage_df[selected_columns]

In [210]:
cov_df.rename(columns={'mean_score': 'revenue'}, inplace=True)

/var/folders/1_/8z7nsr3d0_d_4g3l303jw0yh0000gp/T/ipykernel_34455/429951063.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cov_df.rename(columns={'mean_score': 'revenue'}, inplace=True)

In [211]:
cov_df.head()

,ppg_nm,retailer_id,ppg_retailer,MAPE,R2 Score,Beta,final_flag,revenue
0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,True,False,162.574052
1,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,HY-VEE,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,True,False,26.687255
2,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,MEIJER,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,True,False,6.472653
3,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,OTHER TOTAL US FOOD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,True,False,7647.868810
4,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,MEIJER,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,True,False,2742.341046

In [188]:
cov_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3625 entries, 0 to 3624
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ppg_nm        3625 non-null   object
 1   retailer_id   3625 non-null   object
 2   ppg_retailer  3625 non-null   object
 3   MAPE          3625 non-null   bool
 4   R2 Score      3625 non-null   bool
 5   Beta          3625 non-null   bool
 6   revenue       3625 non-null   float64
dtypes: bool(3), float64(1), object(3)
memory usage: 152.2+ KB

In [212]:
total_revenue = cov_df.groupby('ppg_nm')['revenue'].transform('sum')

In [213]:
cov_df['coverage'] = (cov_df['revenue'] / total_revenue)* 100

In [214]:
cov_df.head(10)

,ppg_nm,retailer_id,ppg_retailer,MAPE,R2 Score,Beta,final_flag,revenue,coverage
0,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,AHOLD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,True,False,162.574052,2.072696
1,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,HY-VEE,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,True,False,26.687255,0.340242
2,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,MEIJER,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,False,False,True,False,6.472653,0.082521
3,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,OTHER TOTAL US FOOD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,True,False,7647.868810,97.504540
4,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,MEIJER,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,True,False,2742.341046,76.705062
5,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,OTHER TOTAL US FOOD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,True,False,832.835052,23.294938
6,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,MEIJER,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,True,False,2801.241438,95.051897
7,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,OTHER TOTAL US FOOD,AIR TREATMENT | AEROSOL | AE OZIUM | AE OZIUM ...,True,False,True,False,145.823812,4.948103
8,AIR TREATMENT | AEROSOL | LYSOL | LYSOL NEUTRA...,AHOLD,AIR TREATMENT | AEROSOL | LYSOL | LYSOL NEUTRA...,True,True,True,True,3726.505373,9.066850
9,AIR TREATMENT | AEROSOL | LYSOL | LYSOL NEUTRA...,ALBSCO,AIR TREATMENT | AEROSOL | LYSOL | LYSOL NEUTRA...,True,True,True,True,2884.597732,7.018430

In [215]:
path = '/Users/pradeep/Downloads/cov.csv'  
cov_df.to_csv(path)